services:
  vue-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vue-chat-app
    restart: unless-stopped
    ports:
      - '80:80'  # Keep this as you want
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1'
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - frontend-network

networks:
  frontend-network:
    driver: bridge